"""add invoice sequence column

Revision ID: 54bbcabaf343
Revises: d114b4006251
Create Date: 2026-08-31 08:34:03.666681

"""

import re
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54bbcabaf343'
down_revision: Union[str, None] = 'd114b4006251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Hand-adjusted from the autogenerated version: autogenerate only emitted a
# plain `nullable=False` add_column, which fails outright against any table
# that already has rows (and leaves them with no real sequence value even if
# it didn't). Instead this adds the column nullable, backfills it for any
# pre-existing rows by parsing the trailing digits off their `number` (the
# same numeric tail `_next_invoice_number` used to format), then tightens
# the column to NOT NULL. SQLite can't ALTER COLUMN directly, hence the
# batch_alter_table.
_number_tail_re = re.compile(r"(\d+)$")


def upgrade() -> None:
    op.add_column("invoices", sa.Column("sequence", sa.Integer(), nullable=True))

    connection = op.get_bind()
    invoices = sa.table(
        "invoices",
        sa.column("id", sa.Integer),
        sa.column("number", sa.String),
        sa.column("sequence", sa.Integer),
    )
    for invoice_id, number in connection.execute(sa.select(invoices.c.id, invoices.c.number)):
        match = _number_tail_re.search(number or "")
        sequence_value = int(match.group(1)) if match else 0
        connection.execute(
            invoices.update().where(invoices.c.id == invoice_id).values(sequence=sequence_value)
        )

    with op.batch_alter_table("invoices") as batch_op:
        batch_op.alter_column("sequence", existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    with op.batch_alter_table("invoices") as batch_op:
        batch_op.drop_column("sequence")
